export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_USER_FAILED = 'NEW_USER_FAILED';

export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILED = 'SIGN_IN_USER_FAILED';

export const USER_LOG_OUT = 'USER_LOG_OUT';

export const USER_AUTH_TOKEN_SUCCESS = 'USER_AUTH_TOKEN_SUCCESS';
export const USER_AUTH_TOKEN_FAILED = 'USER_AUTH_TOKEN_FAILED';
